version: '3'

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - all

  all:
    desc: 'Build and test everything'
    deps:
      - test

  build:
    desc: 'Build all components'
    deps:
      - build-regular

  build-regular:
    desc: 'Build the Regular binary'
    cmds:
      - cmd: go build -trimpath
    sources:
      - '*.go'
    generates:
      - regular

  clean:
    desc: 'Clean up binaries'
    cmds:
      - rm -f regular regular.exe

  release:
    desc: 'Prepare a release'
    deps:
      - build-regular
    cmds:
      - VERSION=$(./regular{{exeExt}} --version) go run script/release.go

  test:
    desc: 'Run tests'
    deps:
      - build-regular
    cmds:
      - go test ./...
